'tooling'
'ps versions / installation'
'get-help / get-command'
'modules'
'get-process / get-service'
'ps-provider /ps-drive'
'get-item / new-item / get-childitem / ...'
'registry / certificate manager'
'interop (ipconifg, driverquery)'
'stdin / stderr / exit code'
'Formating / regex / convert-from / create ps objects'
'start-process / wait for process / -minimize, -maximize'
'pipelines / select / where (case sensitive -ceq -cne || -ine -ieq )/ sorting / foreach / group / measure-object'
'Get-Member'
'Functions'
'Modules'

# not relevant
'com interfaces'
'win ps remoting'